services:
#Twig Extensions
    sbs_adminlte.twig.nav_bar_extension:
        class: SbS\AdminLTEBundle\Twig\NavBarExtension
        arguments: ["@event_dispatcher", "%kernel.root_dir%"]
        tags:
            - { name: twig.extension }

    sbs_adminlte.twig.sidebar_extension:
        class: SbS\AdminLTEBundle\Twig\SideBarExtension
        arguments: ["@event_dispatcher"]
        tags:
            - { name: twig.extension }

##Demo Event Listeners uncomment for demo
#    sbs_adminlte.user_listener:
#        class: SbS\AdminLTEBundle\EventListener\UserEventListener
#        tags:
#            - { name: kernel.event_listener, event: sbs.admin_lte.user, method: onShowUser }
#
#    sbs_adminlte.tasks_listener:
#        class: SbS\AdminLTEBundle\EventListener\TaskListEventListener
#        tags:
#            - { name: kernel.event_listener, event: sbs.admin_lte.tasks, method: onListTasks }
#
#    sbs_adminlte.notifications_listener:
#        class: SbS\AdminLTEBundle\EventListener\NotificationListEventListener
#        tags:
#            - { name: kernel.event_listener, event: sbs.admin_lte.notifications, method: onListNotifications }
#
#    sbs_adminlte.sidebar_menu_listener:
#        class: SbS\AdminLTEBundle\EventListener\SidebarMenuEventListener
#        tags:
#            - { name: kernel.event_listener, event: sbs.admin_lte.sidebar_menu, method: onShowMenu }
